version: 2

project_name: katalog

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: katalog
    binary: katalog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # This handles your requirement: zip for windows, tar.gz for others
    format: tar.gz
    formats:
      - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: alessandrocaglio
    name: katalog

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Simplified dockers_v2 block
dockers_v2:
  - id: katalog
    # GoReleaser will push quay.io/user/katalog:v0.0.6 AND quay.io/user/katalog:latest
    images:
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog"
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Containerfile