project_name: katalog

before:
  hooks:
    - go mod tidy
    - go test ./...

# Build binaries
builds:
  - id: katalog
    binary: katalog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

# Archives for release
archives:
  - builds:
      - katalog
    format_overrides:
      - goos: windows
        format: zip

# Checksums
checksum:
  name_template: "checksums.txt"

# GitHub Release
release:
  github:
    owner: alessandrocaglio
    name: katalog

# Changelog generation
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Docker images
dockers:
  - image_templates:
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:{{ .Tag }}-amd64"
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:latest-amd64"
    goarch: amd64
    dockerfile: Containerfile
    push: true

  - image_templates:
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:{{ .Tag }}-arm64"
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:latest-arm64"
    goarch: arm64
    dockerfile: Containerfile
    push: true

docker_manifests:
  - name_template: "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:{{ .Tag }}"
    image_templates:
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:{{ .Tag }}-amd64"
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:{{ .Tag }}-arm64"
    push: true

  - name_template: "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:latest"
    image_templates:
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:latest-amd64"
      - "quay.io/{{ .Env.QUAY_USERNAME }}/katalog:latest-arm64"
    push: true
